package com.xiaomi.dao;

import com.xiaomi.entry.GoodsImage;
import com.xiaomi.entry.GoodsImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    long countByExample(GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int deleteByExample(GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int insert(GoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int insertSelective(GoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    List<GoodsImage> selectByExample(GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    GoodsImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsImage record, @Param("example") GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByExample(@Param("record") GoodsImage record, @Param("example") GoodsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByPrimaryKey(GoodsImage record);
}