package com.xiaomi.dao;

import com.xiaomi.entry.GoodsShoppingAddress;
import com.xiaomi.entry.GoodsShoppingAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsShoppingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    long countByExample(GoodsShoppingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int deleteByExample(GoodsShoppingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int insert(GoodsShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int insertSelective(GoodsShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    List<GoodsShoppingAddress> selectByExampleWithBLOBs(GoodsShoppingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    List<GoodsShoppingAddress> selectByExample(GoodsShoppingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    GoodsShoppingAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsShoppingAddress record, @Param("example") GoodsShoppingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") GoodsShoppingAddress record, @Param("example") GoodsShoppingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByExample(@Param("record") GoodsShoppingAddress record, @Param("example") GoodsShoppingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(GoodsShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopping_address
     *
     * @mbg.generated Thu Jun 11 21:31:19 CST 2020
     */
    int updateByPrimaryKey(GoodsShoppingAddress record);
}